#!/usr/bin/with-contenv bash

if [ ! "$EDGE" = "1" ]; then
  echo "EDGE not requested, keeping stable version"
else
  echo "EDGE requested, updating to latest version"
  wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sh /dev/stdin
fi
